version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  jspdockersample:
    image: jspdockersample:latest
    container_name: jspdockersample
    expose:
      - "8080"
    cap_add:
      - NET_ADMIN
